apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaling-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaling-test
  template:
    metadata:
      labels:
        app: scaling-test
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        automountServiceAccountToken: false
      containers:
      - name: scaling-test
        image: busybox:1.36
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
