name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ latest

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4  # ✅ upgraded
        with:
          node-version: '18'
          cache: 'npm'  # ✅ Enables node_modules caching automatically

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run tests
        working-directory: ./backend
        run: npm test
