name: SonarCloud Frontend Scan

on:
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for PR metadata

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies and run tests
        run: |
          cd frontend
          npm ci
          npm test -- --coverage --watchAll=false

      - name: SonarCloud Scan (Frontend only)
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=mt-org
            -Dsonar.projectKey=mt-org
            -Dsonar.sources=frontend/src
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.js
            -Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
            -Dsonar.coverage.exclusions=**/*.test.js,**/__tests__/**,**/__mocks__/**
            -Dsonar.qualitygate.wait=true
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
