name: SonarCloud

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

jobs:
  sonarqube:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=mt-org
            -Dsonar.projectKey=mt-org
            -Dsonar.sources=frontend/src
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.js
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
