name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run SonarCloud Scan
        working-directory: ./backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.organization=mt-org \
            -Dsonar.projectKey=mt-org \
            -Dsonar.branch.name=main \
            -Dsonar.sources=. \
            -Dsonar.exclusions=node_modules/**,dist/**,**/*.spec.js
