name: SonarCloud

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

jobs:
  sonarqube:
    name: SonarCloud Scan with Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run tests and collect coverage
        working-directory: ./frontend
        run: npm test -- --coverage

      - name: Upload coverage to SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=mt-org
            -Dsonar.projectKey=mt-org
            -Dsonar.sources=frontend/src
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.js
            -Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
            -Dsonar.coverage.exclusions=**/*.test.js,**/__tests__/**,**/__mocks__/**
            -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
